# Generated by Django 5.1.5 on 2025-01-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "movieName",
                    models.CharField(default="", max_length=255, verbose_name="电影名"),
                ),
                (
                    "commentContent",
                    models.CharField(
                        default="", max_length=255, verbose_name="电影评论"
                    ),
                ),
            ],
            options={
                "db_table": "comments",
            },
        ),
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "detailLink",
                    models.CharField(
                        default="", max_length=255, verbose_name="详情链接"
                    ),
                ),
                (
                    "rate",
                    models.CharField(default="", max_length=255, verbose_name="评分"),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=255, verbose_name="电影名"),
                ),
                (
                    "cover",
                    models.CharField(default="", max_length=255, verbose_name="封面"),
                ),
                (
                    "year",
                    models.CharField(default="", max_length=255, verbose_name="年份"),
                ),
                (
                    "types",
                    models.CharField(default="", max_length=255, verbose_name="类型"),
                ),
                (
                    "country",
                    models.CharField(default="", max_length=255, verbose_name="国家"),
                ),
                (
                    "language",
                    models.CharField(default="", max_length=255, verbose_name="语言"),
                ),
                (
                    "time",
                    models.CharField(default="", max_length=255, verbose_name="时间"),
                ),
                (
                    "movieTime",
                    models.CharField(
                        default="", max_length=255, verbose_name="电影时长"
                    ),
                ),
                (
                    "comment_len",
                    models.CharField(default="", max_length=255, verbose_name="评论量"),
                ),
                (
                    "stars",
                    models.CharField(default="", max_length=255, verbose_name="星级"),
                ),
                (
                    "summary",
                    models.CharField(default="", max_length=255, verbose_name="简述"),
                ),
                (
                    "comments",
                    models.CharField(
                        default="", max_length=255, verbose_name="5条评论"
                    ),
                ),
                (
                    "imgList",
                    models.CharField(
                        default="", max_length=255, verbose_name="图片链接"
                    ),
                ),
                (
                    "movieUrl",
                    models.CharField(
                        default="", max_length=255, verbose_name="视频链接"
                    ),
                ),
                (
                    "createTime",
                    models.DateField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "db_table": "movies",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "userName",
                    models.CharField(default="", max_length=255, verbose_name="用户名"),
                ),
                (
                    "password",
                    models.CharField(default="", max_length=255, verbose_name="密码"),
                ),
                (
                    "info",
                    models.CharField(
                        default="", max_length=255, verbose_name="个人描述"
                    ),
                ),
                (
                    "avatar",
                    models.FileField(
                        default="avatar/default.png",
                        upload_to="avatar",
                        verbose_name="用户头像",
                    ),
                ),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
