# Generated by Django 5.1.5 on 2025-01-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="comments",
            field=models.CharField(default="", max_length=2555, verbose_name="评论"),
        ),
        migrations.AlterField(
            model_name="movies",
            name="imgList",
            field=models.TextField(blank=True, null=True, verbose_name="图片列表"),
        ),
        migrations.AlterField(
            model_name="movies",
            name="summary",
            field=models.CharField(default="", max_length=2555, verbose_name="简述"),
        ),
    ]
