# Generated by Django 5.1.5 on 2025-01-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0002_alter_movies_comments_alter_movies_imglist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="movieUrl",
            field=models.TextField(blank=True, null=True, verbose_name="视频链接"),
        ),
    ]
