# Generated by Django 5.1.5 on 2025-01-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0003_alter_movies_movieurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="comments",
            field=models.TextField(blank=True, null=True, verbose_name="图片列表"),
        ),
        migrations.AlterField(
            model_name="movies",
            name="detailLink",
            field=models.TextField(blank=True, null=True, verbose_name="图片列表"),
        ),
        migrations.AlterField(
            model_name="movies",
            name="summary",
            field=models.TextField(blank=True, null=True, verbose_name="图片列表"),
        ),
    ]
