# Generated by Django 5.1.5 on 2025-01-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0004_alter_movies_comments_alter_movies_detaillink_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="commentContent",
            field=models.TextField(blank=True, null=True, verbose_name="电影评论"),
        ),
    ]
