# Generated by Django 5.1.5 on 2025-01-20 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0005_alter_comments_commentcontent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="userName",
            new_name="username",
        ),
    ]
